version: "3.9"

networks:
  wx_net:
    name: wx_net
    
volumes:  
  dynamodb-data:
    driver: local

services: 
  webex_compliance:
    build:
      context: .
      dockerfile: Dockerfile
    command: python wxt_compliance.py -vv -cm
    container_name: app
    depends_on:
      - dynamodb
    ports:
      - "5050:5050"
    environment:
      PYTHONUNBUFFERED: 'true'
      # comma separated list of servers, formats:
      # hostname_or_ip:port/protocol, hostname_or_ip:port, hostname_or_ip
      SYSLOG_SERVERS: "127.0.0.1:514/udp"
      # syslog facility, values:
      # CLOCK, CLOCK2, FTP, KERNEL, LOCAL0, LOCAL1, LOCAL2, LOCAL3, LOCAL4, LOCAL5, LOCAL6, LOCAL7,
      # LOG_ALERT, LOG_AUDIT, MAIL, NETWORK, NTP, PRINTER, SECURITY, SYSLOG, SYSTEM, USER, UUCP
      SYSLOG_FACILITY: "network"
      # syslog severity, values:
      # ALERT, CRITICAL, DEBUG, EMERGENCY, ERROR, INFO, NOTICE, WARNING
      SYSLOG_SEVERITY: "info"
      # WEBEX_INTEGRATION_ID: "paste_your_integration_id_here"
      # WEBEX_INTEGRATION_CLIENT_ID: "paste_your_integration_client_id_here"
      # WEBEX_INTEGRATION_CLIENT_SECRET: "paste_your_integration_client_secret_here"
    env_file:
      - '.env_docker'
    restart: always
    networks:
      - wx_net
    image: jardamartan/wx_compliance

  dynamodb:
    build:
      context: .
      dockerfile: Dockerfile-dynamo
    image: dynamo
    container_name: dynamodb
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data
    restart: always
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - wx_net
